-- DISEÑO FÍSICO
create database empresa;
use empresa;
-- CENTROS
CREATE TABLE CENTROS (
    NUMCE INT(4) PRIMARY KEY,
    NOMCE VARCHAR(30), 
    DIRCE VARCHAR(30) );

-- DEPARTAMENTOS 
CREATE TABLE DEPARTAMENTOS ( 
    NUMDE INT(3) PRIMARY KEY,
    NUMCE INT(4),
    DIREC INT(3),
    TIDIR CHAR(1), 
    PRESU decimal(3,1), 
    DEPDE INT(3) , 
    NOMDE VARCHAR(30),
    FOREIGN KEY(NUMCE)
		REFERENCES CENTROS(NUMCE),
	FOREIGN KEY(DEPDE)
		REFERENCES DEPARTAMENTOS(NUMDE)
);

-- EMPLEADOS
CREATE TABLE EMPLEADOS (
    NUMEM INT(3) PRIMARY KEY,
    EXTEL INT(3), 
    FECNA DATE, 
    FECIN DATE, 
    SALAR INT(5), 
    COMIS INT(3), 
    NUMHI INT(1), 
    NOMEM VARCHAR(30), 
    NUMDE INT(3) ,
    FOREIGN KEY(NUMDE)
		REFERENCES DEPARTAMENTOS (NUMDE)
);
