import random
import re
import unicodedata

ahorcado={"Películas":{
"El padrino",
"El caballero oscuro",
"Titanic",
"Forrest Gump",
"Jurassic Park",
"El silencio de los corderos",
"Star Wars: El retorno del jedi",
"Pulp Fiction",
"Los Vengadores: Endgame",
"Regreso al futuro",
"Matrix",
"Gladiator",
"La lista de Schindler",
"Avatar",
"El señor de los anillos: las dos torres",
"Indiana Jones y la última cruzada",
"Volver",
"El gran Lebowski",
"Cadena perpetua",
"Casablanca",
"El planeta de los simios",
"Rocky",
"Kill Bill",
"Mad Max",
"Grease",
"Cazafantasmas",
"E.T.",
"El resplandor",
"La naranja mecánica",
"Indiana Jones en busca del arca perdida",
"Toy Story",
"Shrek",
"Harry Potter y la cámara secreta",
"Spider-Man: Homecoming",
"V de vendeta",
"Piratas del Caribe: La maldición de La Perla Negra",
"Terminator",
"El club de la lucha",
"Memento",
"Alien",
"Blade Runner",
"Amélie",
"Sin City",
"Los increíbles",
"Ratatouille",
"Coco",
"Los juegos del hambre",
"Guardianes de la galaxia",
"Doctor Strange",
"Black Panther",
"John Wick",
"El lobo de Wall Street",
"Interestelar",
"Django desencadenado",
"Origen",
"La forma del agua",
"Parásitos",
"Joker",
"Whiplash",
"La La Land",
"El pianista",
"La vida es bella",
"Donnie Darko",
"Una mente maravillosa",
"Her",
"La teoría del todo",
"El gran hotel Budapest",
"Bohemian Rhapsody",
"Rocketman",
"Moulin Rouge",
"Chicago",
"El rey león",
"Buscando a Nemo",
"Up",
"Frozen",
"Enredados",
"Del revés",
"Vaiana",
"El viaje de Chihiro",
"Akira",
"Los siete samuráis",
"Amores perros",
"Ciudad de Dios",
"El laberinto del fauno",
"Un monstruo viene a verme",
"Roma",
"Slumdog Millionaire",
"El renacido",
"El emperador y sus locuras",
"El perfume",
"El quinto elemento"
"El truco final",
"Big Fish",
"Mejor imposible",
"La isla mínima",
"Todo sobre mi madre",
"La historia interminable",
"Gremlins",
"Critters",
"La novia cadaver",
"Pesadilla antes de navidad",
"La sirenita",
"Aladdin",
"Sonrisas y lágrimas",
"Mary Poppins",
"The end of Evangelion",
"El castillo ambulante",
"Call me by your name",
"Your name",
"Brokeback mountain",
"Hairspray",
"Tenet",
"La momia",
"Crepúsculo",
"El corredor del laberinto",
"Kárate a muerte en Torremolinos",
"It",
"Insidious",
"Scream",
"Scary movie",
"El orfanato",
"Malditos bastardos",
"La boda de mi mejor amigo",
"El bar Coyote",
"Pretty woman",
"Algo pasa con Mary",
"Ace Ventura: detective de mascotas",
"La máscara",
"El show de Truman",
"Blancanieves",
"Blancanieves: la leyenda del cazador",
"Pokémon: el poder de todos",
"Digimon: la película",
"La mano que mece la cuna",
"Alguien voló sobre el nido del cuco",
"Pájaros",
"Psicosis",
"Dragón rojo",
"Seven",
"El coleccionista de huesos",
"Los padres de ella",
"Aterriza como puedas",
"Loca academia de policía",
"Scott Pilgrim"},
"Series":{
"Breaking Bad",
"Juego de tronos",
"Friends",
"The Office",
"Stranger things",
"The Mandalorian",
"Chernobyl",
"The Crown",
"Black Mirror",
"The Big Bang Theory",
"Sherlock",
"House of Cards",
"Better Call Saul",
"How I Met Your Mother",
"The Walking Dead",
"Westworld",
"True Detective",
"Narcos",
"Vikings",
"Perdidos",
"Mad Men",
"Suits",
"Los Simpson",
"Futurama",
"Rick y Morty",
"Bojack Horseman",
"South Park",
"American Horror Story",
"Doctor Who",
"The Boys",
"Lucifer",
"Dark",
"Peaky Blinders",
"Dexter",
"Prison Break",
"The Witcher",
"Los Soprano",
"Gossip Girl",
"Anatomía de Grey",
"Buffy, cazavampiros",
"Smallville",
"Supernatural",
"Arrow",
"Daredevil",
"Jessica Jones",
"Agentes de SHIELD",
"The Umbrella Academy",
"Gotham",
"El cuento de la criada",
"Star Trek",
"Firefly",
"Battlestar Galactica",
"Fargo",
"Mr. Robot",
"Brooklyn Nine-Nine",
"Modern Family",
"Malcolm in the Middle",
"The Good Place",
"Roma",
"House",
"Expediente X",
"Twin Peaks",
"Castle",
"Fringe",
"Hannibal",
"True Blood",
"The Wire",
"La casa de papel"
"Élite"
"Merlí"
"Los Serrano",
"Aquí no hay quien viva",
"La que se avecina",
"Curro Jiménez",
"Farmacia de guardia",
"Médico de familia",
"Un paso adelante",
"Compañeros",
"Física o química",
"Al salir de clase",
"Periodistas",
"Hospital central",
"Urgencias",
"Rex, un policía diferente",
"Motivos personales",
"MacGyver",
"Heartstopper",
"He-man y los Masters del universo"
"She-ra, la princesa del poder"
"Power Rangers",
"Pokémon",
"Dragon Ball",
"Dragon Ball Z",
"Dragon Ball Super",
"One Piece",
"Naruto",
"Bleach",
"Cosas de casa",
"Sabrina, cosas de brujas",
"Orange is the new black",
"Vis a vis",
"Veneno",
"Paquita Salas",
"Smiley",
"Steven Universe",
"Hora de aventuras",
"Queer as folk",
"Scott Pilgrim da el salto",
"The last of us",
"El súper",
"Amar en tiempos revueltos",
"Amar es para siempre",
"Arrayán",
"Dinastía",
"Dallas",
"Punky Brewster",
"The White Lotus",
"La casa de las flores",
"Glee",
"Vestidas de azul",
"Looking",
"Phineas y Ferb",
"Doraemon",
"Shinchan",
"Saint Seiya",
"Cardcaptor Sakura",
"Sailor Moon",
"Yaiba",
"Detective Conan",
"Candy Candy",
"Chicho Terremoto",
"Los Trotamúsicos",
"Los Fruittis",
"Delphi",
"D'Artacán y los tres mosqueperros",
"David el gnomo",
"Aída",
"Siete vidas",
"X-men"},
"Música":{
"The Beatles",
"Queen",
"Led Zeppelin",
"The Rolling Stones",
"Pink Floyd",
"AC/DC",
"Metallica",
"Nirvana",
"Coldplay",
"Radiohead",
"Red Hot Chili Peppers",
"The Doors",
"The Police",
"Guns N' Roses",
"Aerosmith",
"The Who",
"Green Day",
"Foo Fighters",
"Linkin Park",
"Imagine Dragons",
"Arctic Monkeys",
"Muse",
"The Killers",
"My Chemical Romance",
"Bon Jovi",
"Iron Maiden",
"Rammstein",
"The Cure",
"Depeche Mode",
"David Bowie",
"Bruce Springsteen",
"Bob Dylan",
"Prince",
"Michael Jackson",
"Madonna",
"Whitney Houston",
"Mariah Carey",
"Beyoncé",
"Rihanna",
"Lady Gaga",
"Britney Spears",
"Justin Timberlake",
"Justin Bieber",
"Taylor Swift",
"Ed Sheeran",
"Drake",
"Eminem",
"Jay-Z",
"Kanye West",
"Post Malone",
"Billie Eilish",
"Dua Lipa",
"Harry Styles",
"The Weeknd",
"Selena Gomez",
"Shakira",
"Jennifer Lopez",
"Rosalía",
"Bad Bunny",
"Daddy Yankee",
"Maluma",
"J Balvin",
"Anuel AA",
"Ozuna",
"Karol G",
"Camila Cabello",
"Luis Fonsi",
"Enrique Iglesias",
"Alejandro Sanz",
"Maná",
"Juanes",
"Aventura",
"Marc Anthony",
"Ricky Martin",
"Elvis Presley",
"Frank Sinatra",
"Johnny Cash",
"Elton John",
"Stevie Wonder",
"Aretha Franklin",
"Tina Turner",
"The Supremes",
"ABBA",
"Bee Gees",
"The Beach Boys",
"The Clash",
"Ramones",
"Sex Pistols",
"Skrillex",
"Joy Division",
"Gorillaz",
"Daft Punk",
"The Chemical Brothers",
"La Oreja de Van Gogh",
"Amaia Montero",
"Mecano",
"Malú",
"Pablo López",
"Pablo Alborán",
"Amaral",
"El sueño de Morfeo",
"Maldita Nerea",
"Vetusta Morla",
"Rigoberta Bandini",
"Efecto Mariposa",
"La quinta estación",
"Melocos",
"Iguana Tango",
"Dani Fernández",
"Blas Cantó",
"Auryn",
"Isabel Pantoja",
"Rocío Jurado"
"Yurena",
"Dani Martín",
"David Otero",
"El canto del loco",
"Despistaos",
"Miriam Rodríguez",
"Cepeda",
"Virginia Maestro",
"Chenoa",
"David Bisbal",
"David Bustamante",
"Rosa López",
"Mario Jeferson",
"Aitana",
"Sebastián Yatra",
"Amaia Romero",
"Alfred García",
"Santa Justa Klan",
"UPA Dance",
"Marifé de Triana",
"Miguel Bosé",
"Carlos Cano",
"María Dolores Pradera",
"María del Monte",
"María Jiménez",
"Joaquín Sabina",
"José Luis Perales",
"Nino Bravo",
"Camilo Sesto",
"El Fary",
"Los del Río",
"Mocedades",
"Soraya Arnelas",
"Ruth Lorenzo",
"Gabinete Caligari",
"El último de la fila",
"Manolo García",
"Los Secretos",
"Avantasia",
"Flos Mariae",
"Hidrogenesse",
"Destripando la historia",
"Ojete Calor",
"Vanesa Martín",
"Conchita",
"Rozalén",
"Laura Pausini",
"Paulina Rubio",
"Rosario Flores",
"Ana Belén",
"Amistades peligrosas",
"Gloria Estefan",
"Pibull",
"La mosca tse-tse",
"Manuel Carrasco",
"Estopa",
"Los Delinqüentes",
"Fran Perea",
"Chanel",
"Angy Fernández",
"Rocco",
"Megara",
"Edurne",
"Beth",
"La casa azul",
"Paul Thin",
"Naiara",
"Las Bistec",
"Nancys Rubias",
"Fangoria",
"Julio Iglesias",
"Rick Astley",
"Destripando la historia",
"Quevedo",
"Mónica Naranjo",
"Ana Torroja",
"Nanase Aikawa",
"Hikaru Utada",
"Shironobu Kageyama",
"Ayumi Hamasaki",
"Zard",
"Siam Shade",
"L'Arc~en~Ciel",
"IZAL",
"Mike Izal"    
"Rauw Alejandro",
"Feid",
"Bizarrap",
"C. Tangana",
"Myke Towers",
"Mora",
"Duki",
"María Becerra",
"Yung Beef",
"Morad",
"Don Patricio",
"Recycled J",
"Lola Índigo",
"Álvaro de Luna"    
"Nathy Peluso",
"Nicki Nicole",
"Ayax",
"Eladio Carrión",
"Omar Montes",
"Natos y Waor",
"Maikel Delacalle",
"Recycled J",
"Melendi",
"Bad Gyal",
"Zzoilo",
"Ana Mena",
"Manuel Turizo",
"Becky G",
"Paulo Londra",
"Hens"
"Saiko",
"Cruz Cafuné",
"Beret",
"RVFV",
"Dellafuente",
"Rels B",
"Pol Granch",
"Trueno",
"Guitarricadelafuente",
"Juancho Marqués",
"Reik",
"Sebastián Cortés",
"Zetazen",
"Kidd Keo",
"Hoke",
"Fernando Costa",
"Anaju",
"Nil Moliner",
"Walls",
"Lérica",
"Pole",
"Khea",
"Lola Índigo",
"Sen Senra",
"Choclock",
"La M.O.D.A.",
"Zetak",
"Oques Grasses",
"Arnau Griso",
"Alizzz",
"Recycled J",
"Funambulista",
"Belén Aguilera",
"Soge Culebra",
"Marmi",
"Ptazeta",
"Haze",
"Marc Seguí",
"Pole",
"Jaime Lorente",
"Rojuu",
"Albany",
"MDA",
"Aleesha Rose"
"Tote King",
"Hard GZ",
"Porta",
"SFDK",
"Almácor",
"Hayden Panettiere",
"Snow Patrol",
"Ashley Tisdale",
"Christina Aguilera",
"Spice Girls",
"Backstreet Boys",
"NSYNC",
"Take That"
}
}

def iniciaAhorcado():
    categoria = random.choice(list(ahorcado.keys()))
    adivina = random.choice(list(ahorcado[categoria]))
    texto_normalizado = unicodedata.normalize('NFD', adivina)

    # Filtramos eliminando los diacríticos, pero conservando la "ñ"
    texto_sin_tildes = ''.join(
        char for char in texto_normalizado if unicodedata.category(char) != 'Mn' or char == 'ñ'
    )
    adivinaLower = texto_sin_tildes.lower()
    adivinaOculto = re.sub(r'[a-zñ]', '_', adivinaLower)

    return [categoria, adivina, adivinaLower, adivinaOculto]